name: Github Action Content
on: [push]
jobs:
  Copy-Content:
    runs-on: ubuntu-latest
    steps:
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: /Groupdocs.Blog/
          dst_path: /content/
          dst_owner: groupdocs
          dst_repo_name: groupdocs-blog
          dst_branch: master